from __future__ import annotations

import asyncio
import json
import os
import re
from collections import defaultdict
from typing import Any, Dict, Iterable, List, Optional

import torch

from verl import DataProto
from verl.workers.reward_manager import register


DEFAULT_QA_JUDGE_PROMPT = """You are an expert data analysis evaluator. Your task is to evaluate the quality of a set of analytical findings (claims) generated by an AI agent in response to a specific question. You will be provided with the user's question, the ground truth (golden answer), and the agent's generated claims.

Please evaluate the agent's claims based on how well they align with the golden answer.

### Evaluation Criteria:
1. Accuracy: Do the claims state facts that are correct according to the golden answer?
2. Completeness: Did the agent capture the core message and key points of the golden answer?
3. Hallucination: Did the agent invent data points, trends, or facts that contradict or are unsupported by the golden answer?

### Scoring Rubric (0-3):
* [3] Excellent (Fully Accurate & Complete): The claims perfectly capture the key points of the golden answer. There are no factual errors, no severe omissions, and zero hallucinations.
* [2] Partial (Minor Errors or Omissions): The claims capture the core of the golden answer but miss some minor details, or include slight, harmless extra information. No severe hallucinations or direct contradictions.
* [1] Poor (Severe Errors or Hallucinations): The claims contain significant factual errors, contradict the golden answer, miss the primary core message, or suffer from major hallucinations.
* [0] Invalid: The response is entirely empty, nonsensical, or completely unrelated to the question.

### Input Data:
[Question]: {question}
[Golden Answer]: {golden_answer}
[Agent Output]: 
{agent_claims}

### Output Format:
You must output your evaluation in the following JSON format. Provide a concise step-by-step reasoning BEFORE giving the final integer score.
{{
  "reasoning": "Briefly compare the claims against the golden answer based on accuracy, completeness, and hallucination.",
  "score": <int between 0 and 3>
}}"""


DEFAULT_RESEARCH_JUDGE_PROMPT = """You are a Senior Data Scientist and an expert evaluator. Your task is to evaluate the quality of exploratory data analysis findings (claims) generated by an AI agent for an open-ended research topic. There is no predefined correct answer.

Please evaluate the agent's claims based on their analytical value, logical soundness, and relevance to the research topic.

### Evaluation Criteria:
1. Relevance: Do the claims directly address the core intent of the research question?
2. Depth & Insightfulness: Do the claims demonstrate deep analytical thinking (e.g., correlations, anomalies), or are they just superficial observations?
3. Logical Soundness: Are the conclusions drawn plausible and logically supported by standard data analysis practices?

### Scoring Rubric (0-3):
* [3] Excellent (Highly Insightful & Logical): Highly relevant and logically sound. The claims go beyond obvious, surface-level observations to provide valuable, deep analytical perspectives.
* [2] Fair (Relevant but Superficial): The claims are relevant and generally logical, but lack analytical depth. They mostly state obvious facts or simple summaries without extracting deeper insights.
* [1] Poor (Flawed or Irrelevant): The claims draw highly questionable or illogical conclusions, lack structural coherence, or fail to meaningfully address the core research topic.
* [0] Invalid: The response is entirely empty, nonsensical, or completely ignores the research topic.

### Input Data:
[Research Topic / Question]: {question}
[Agent Output]: 
{agent_claims}

### Output Format:
You must output your evaluation in the following JSON format. Provide a concise step-by-step reasoning BEFORE giving the final integer score.
{{
  "reasoning": "Briefly evaluate the claims focusing on relevance, analytical depth, and logical soundness.",
  "score": <int between 0 and 3>
}}"""


DEFAULT_INFER_JUDGE_PROMPT = """You are an expert evaluator for natural language inference in a claim-based data analysis workflow.

Your task is to evaluate whether a single infer step is logically valid based on its premises.

You will be given:
1. The original user question
2. A set of premise claims
3. The inferred conclusion
4. The reasoning text

Your job is to assign a score:

### Scoring Rules
* [1] Good inference
  - The conclusion is supported by the premises.
  - The reasoning is logically sound and faithful to the premises.
  - No unsupported leap, hallucination, contradiction, or speculative extension is introduced.

* [-1] Bad inference
  - The conclusion is not supported by the premises, or overstates what the premises justify.
  - The reasoning introduces unsupported assumptions, speculative causal interpretation, hidden leaps, contradiction, or distortion.

### Important Instructions
- Judge ONLY whether this infer step itself is valid from the premises.
- Do NOT judge based on whether the final answer is correct.
- If the conclusion adds new causal/mechanistic/speculative interpretation not grounded in the premises, assign -1.
- Be conservative: assign 1 only when the inference is clearly justified by the premises.

### Input Data
[Question]: {question}

[Premises]:
{premises_text}

[Conclusion]:
{conclusion}

[Reasoning]:
{reasoning}

### Output Format
You must output valid JSON in the following format:
{
  "reasoning": "Briefly explain whether the conclusion is supported by the premises and whether there is any unsupported leap.",
  "score": 1 or -1
}"""

NEGATIVE_TERMINATION_REASONS = {
    "missing_submit",
    "max_turns",
    "generation_length",
}

def _as_plain_object(value: Any) -> Any:
    if hasattr(value, "tolist"):
        return value.tolist()
    return value


def _is_research_dir_id(dir_id: Any) -> bool:
    return "research" in str(dir_id or "").lower()


def _to_text(value: Any) -> str:
    value = _as_plain_object(value)
    if isinstance(value, str):
        return value
    return json.dumps(value, ensure_ascii=False, indent=2)


def _coerce_text(value: Any) -> str:
    value = _as_plain_object(value)
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    if isinstance(value, list):
        return "".join(_coerce_text(item) for item in value)
    if isinstance(value, dict):
        if "text" in value:
            return _coerce_text(value.get("text"))
        if "content" in value:
            return _coerce_text(value.get("content"))
    return str(value)


def _extract_judge_response_text(response: Any) -> str:
    response = _as_plain_object(response)
    if isinstance(response, (str, bytes)):
        return _coerce_text(response)

    if isinstance(response, dict):
        choices = response.get("choices")
        if isinstance(choices, list) and choices:
            first_choice = _as_plain_object(choices[0])
            if isinstance(first_choice, dict):
                message = _as_plain_object(first_choice.get("message"))
                if isinstance(message, dict):
                    return _coerce_text(message.get("content"))
        return _coerce_text(response.get("content"))

    choices = getattr(response, "choices", None)
    if choices:
        first_choice = choices[0]
        message = getattr(first_choice, "message", None)
        if message is not None:
            return _coerce_text(getattr(message, "content", None))

    return _coerce_text(getattr(response, "content", None))


# def _parse_judge_result(text: str) -> tuple[float, str]:
#     raw = str(text or "").strip()
#     if not raw:
#         return 0.0, "empty_response"
#     try:
#         payload = json.loads(raw)
#     except json.JSONDecodeError:
#         return 0.0, "json_parse_error"
#     score = max(0.0, min(1.0, float(payload.get("score", 0.0))))
#     reason = str(payload.get("reason", "")).strip()
#     return score, reason

def _parse_judge_result(text: str) -> tuple[float, str]:
    raw = str(text or "").strip()
    if not raw:
        return 0.0, "empty_response"
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        return 0.0, "json_parse_error"
    raw_score = payload.get("score", 0.0)
    try:
        raw_score = float(raw_score)
    except Exception:
        raw_score = 0.0
    score = max(0.0, min(1.0, raw_score / 3.0))
    reason = str(payload.get("reasoning") or payload.get("reason") or "").strip()
    return score, reason

def _parse_infer_judge_result(text: str) -> tuple[float, str]:
    raw = str(text or "").strip()
    if not raw:
        return 0, "empty_response"
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        return 0, "json_parse_error"

    raw_score = payload.get("score", 0)
    try:
        raw_score = float(raw_score)
    except Exception:
        raw_score = 0

    score = 1.0 if raw_score >= 0 else -1.0
    reason = str(payload.get("reasoning") or payload.get("reason") or "").strip()
    return score, reason


def _has_ground_truth(value: Any) -> bool:
    if value is None:
        return False
    if isinstance(value, str):
        return value.strip() != ""
    if isinstance(value, (list, tuple, set, dict)):
        return len(value) > 0
    return True

def _extract_infer_steps_from_trajectory(trajectory: Any) -> List[Dict[str, Any]]:
    trajectory = _as_plain_object(trajectory) or []
    if not isinstance(trajectory, list):
        return []

    text_parts = []
    for msg in trajectory:
        msg = _as_plain_object(msg)
        if not isinstance(msg, dict):
            continue
        if msg.get("role") == "assistant":
            content = _coerce_text(msg.get("content", ""))
            if "infer(" in content:
                text_parts.append(content)

    full_text = "\n\n".join(text_parts)
    if not full_text.strip():
        return []

    pattern = re.compile(
        r"""infer\s*\(\s*
            premises\s*=\s*\[(?P<premises>[^\]]*?)\]\s*,\s*
            conclusion\s*=\s*(?P<q1>["']{1,3})(?P<conclusion>.*?)(?P=q1)\s*,\s*
            reasoning\s*=\s*(?P<q2>["']{1,3})(?P<reasoning>.*?)(?P=q2)\s*
            \)""",
        re.DOTALL | re.VERBOSE,
    )

    infer_steps = []
    for m in pattern.finditer(full_text):
        premise_vars = [p.strip() for p in m.group("premises").split(",") if p.strip()]
        infer_steps.append(
            {
                "premise_vars": premise_vars,
                "conclusion": m.group("conclusion").strip(),
                "reasoning": m.group("reasoning").strip(),
            }
        )
    return infer_steps

def _build_claim_var_map(final_claims: List[str]) -> Dict[str, str]:
    return {f"c{i}": str(claim).strip() for i, claim in enumerate(final_claims, start=1)}

def _build_infer_judge_prompt(question: str, premise_texts: List[str], conclusion: str, reasoning: str) -> str:
    premises_text = "\n".join(f"- Premise {i+1}: {p}" for i, p in enumerate(premise_texts)) or "[EMPTY]"
    return (
        "Question:\n"
        f"{question.strip()}\n\n"
        "Premises:\n"
        f"{premises_text}\n\n"
        "Conclusion:\n"
        f"{conclusion.strip() or '[EMPTY]'}\n\n"
        "Reasoning:\n"
        f"{reasoning.strip() or '[EMPTY]'}"
    )


class _AsyncJudgeClient:
    def __init__(
        self,
        model_name: str,
        api_key: str,
        base_url: str,
        max_concurrency: int,
        timeout: int,
        temperature: float,
        max_tokens: int,
    ) -> None:
        from openai import AsyncOpenAI

        self.client = AsyncOpenAI(
            api_key=api_key,
            base_url=base_url,
            timeout=timeout,
        )
        self.model_name = model_name
        self.max_concurrency = max(1, int(max_concurrency))
        self.temperature = float(temperature)
        self.max_tokens = int(max_tokens)

    # async def _score_one(self, payload: Dict[str, str]) -> tuple[float, str]:
    #     try:
    #         response = await self.client.chat.completions.create(
    #             model=self.model_name,
    #             temperature=self.temperature,
    #             max_tokens=self.max_tokens,
    #             messages=[
    #                 {"role": "system", "content": payload["system_prompt"]},
    #                 {"role": "user", "content": payload["user_prompt"]},
    #             ],
    #         )
    #         return _parse_judge_result(_extract_judge_response_text(response))
    #     except Exception as e:
    #         print(f"[WARNING] Judge API call failed: {e}", flush=True)
    #         return 0.0, f"api_error:{type(e).__name__}"

    async def _score_one(self, payload: Dict[str, str], parser) -> tuple[float, str]:
        try:
            response = await self.client.chat.completions.create(
                model=self.model_name,
                temperature=self.temperature,
                max_tokens=self.max_tokens,
                messages=[
                    {"role": "system", "content": payload["system_prompt"]},
                    {"role": "user", "content": payload["user_prompt"]},
                ],
            )
            return parser(_extract_judge_response_text(response))
        except Exception as e:
            print(f"[WARNING] Judge API call failed: {e}", flush=True)
            return -1.0, f"api_error:{type(e).__name__}"

    async def score_many(self, payloads: List[Dict[str, str]], parser) -> List[tuple[float, str]]:
        semaphore = asyncio.Semaphore(self.max_concurrency)

        async def _bounded_score(payload: Dict[str, str]) -> tuple[float, str]:
            async with semaphore:
                return await self._score_one(payload, parser)

        return await asyncio.gather(*[_bounded_score(payload) for payload in payloads])


@register("verigraph")
class VeriGraphRewardManager:
    def __init__(
        self,
        tokenizer,
        max_resp_len=None,
        num_examine=None,
        config=None,
        overlong_buffer_cfg=None,
    ) -> None:
        self.tokenizer = tokenizer
        self.max_resp_len = max_resp_len
        self.config = dict(config or {})
        self.overlong_buffer_cfg = overlong_buffer_cfg

        self.process_weight = float(self.config.get("process_weight", 0.0))
        self.final_weight = float(self.config.get("final_weight", 1))
        self.infer_weight = float(self.config.get("infer_weight", 0.0))
        self.judge_model = str(self.config.get("judge_model") or os.environ.get("VERIGRAPH_JUDGE_MODEL", "")).strip()
        self.judge_api_base = str(self.config.get("judge_api_base") or os.environ.get("VERIGRAPH_JUDGE_API_BASE", "")).strip()
        self.judge_api_key = str(self.config.get("judge_api_key") or os.environ.get("VERIGRAPH_JUDGE_API_KEY", "EMPTY")).strip()
        self.judge_max_concurrency = int(self.config.get("judge_max_concurrency", 16))
        self.judge_timeout = int(self.config.get("judge_timeout", 120))
        self.judge_temperature = float(self.config.get("judge_temperature", 0.0))
        self.judge_max_tokens = int(self.config.get("judge_max_tokens", 256))
        self.qa_judge_prompt = str(self.config.get("qa_judge_prompt") or self.config.get("judge_prompt") or DEFAULT_QA_JUDGE_PROMPT)
        self.research_judge_prompt = str(
            self.config.get("research_judge_prompt") or self.config.get("judge_prompt") or DEFAULT_RESEARCH_JUDGE_PROMPT
        )
        self.infer_judge_prompt = str(
            self.config.get("infer_judge_prompt") or DEFAULT_INFER_JUDGE_PROMPT
        )
        self._judge_client: Optional[_AsyncJudgeClient] = None

        if self.overlong_buffer_cfg is not None:
            assert self.max_resp_len is not None, "max_resp_len must be provided when overlong_buffer_cfg is enabled"

    def _get_judge_client(self) -> _AsyncJudgeClient:
        if not self.judge_model:
            raise ValueError("judge_model must be configured for VeriGraphRewardManager")
        if not self.judge_api_base:
            raise ValueError("judge_api_base must be configured for VeriGraphRewardManager")
        if self._judge_client is None:
            self._judge_client = _AsyncJudgeClient(
                model_name=self.judge_model,
                api_key=self.judge_api_key,
                base_url=self.judge_api_base,
                max_concurrency=self.judge_max_concurrency,
                timeout=self.judge_timeout,
                temperature=self.judge_temperature,
                max_tokens=self.judge_max_tokens,
            )
        return self._judge_client

    def _decode_response(self, data_item) -> tuple[str, int]:
        prompt_ids = data_item.batch["prompts"]
        prompt_length = prompt_ids.shape[-1]
        valid_response_length = int(data_item.batch["attention_mask"][prompt_length:].sum().item())
        valid_response_ids = data_item.batch["responses"][:valid_response_length]
        return self.tokenizer.decode(valid_response_ids, skip_special_tokens=True), valid_response_length

    def _build_judge_prompt(self, question: str, final_claims: Iterable[str], ground_truth: Any) -> str:
        claims_text = "\n".join(f"- {claim}" for claim in final_claims)
        return (
            "Question:\n"
            f"{question.strip()}\n\n"
            "Candidate Final Claims:\n"
            f"{claims_text or '[EMPTY]'}\n\n"
            "Reference Answer:\n"
            f"{_to_text(ground_truth)}"
        )

    def _resolve_judge_prompt_type(self, extra_info: Dict[str, Any]) -> str:
        prompt_type = str(extra_info.get("judge_prompt_type", "") or "").strip().lower()
        if prompt_type in {"qa", "research"}:
            return prompt_type
        return "research" if _is_research_dir_id(extra_info.get("dir_id")) else "qa"

    def _select_system_prompt(self, prompt_type: str) -> str:
        return self.research_judge_prompt if prompt_type == "research" else self.qa_judge_prompt

    # def _score_final_claims_batch(self, judge_payloads: List[Dict[str, str]]) -> List[tuple[float, str]]:
    #     if not judge_payloads:
    #         return []
    #     return asyncio.run(self._get_judge_client().score_many(judge_payloads))

    # def _score_infer_steps_batch(self, judge_payloads: List[Dict[str, str]]) -> List[tuple[float, str]]:
    #     if not judge_payloads:
    #         return []
    #     return asyncio.run(self._get_judge_client().score_many(judge_payloads))

    def _score_final_claims_batch(self, judge_payloads: List[Dict[str, str]]) -> List[tuple[float, str]]:
        if not judge_payloads:
            return []
        return asyncio.run(self._get_judge_client().score_many(judge_payloads, _parse_judge_result))
    
    def _score_infer_steps_batch(self, judge_payloads: List[Dict[str, str]]) -> List[tuple[float, str]]:
        if not judge_payloads:
            return []
        return asyncio.run(self._get_judge_client().score_many(judge_payloads, _parse_infer_judge_result))

    def __call__(self, data: DataProto, return_dict: bool = True):
        # print(data.batch["responses"])
        reward_tensor = torch.zeros_like(data.batch["responses"], dtype=torch.float32)
        reward_extra_info = defaultdict(list)
        judge_debug_info = defaultdict(list)
        total_rewards = []

        trajectory_infos = data.non_tensor_batch.get("trajectory_info", [None] * len(data))
        judge_payloads = []
        judge_lookup = {}
        infer_judge_payloads = []
        infer_judge_lookup = {}

        # Diagnostic counters for judge condition failures
        _diag_total = len(data)
        _diag_no_final_weight = 0
        _diag_invalid_traj = 0
        _diag_not_submitted = 0
        _diag_no_claims = 0
        _diag_no_gt = 0
        _diag_passed = 0

        print(
            f"[DIAG][VeriGraphReward] batch_size={_diag_total}, "
            f"non_tensor_batch_keys={list(data.non_tensor_batch.keys())}, "
            f"process_weight={self.process_weight}, "
            f"infer_weight={getattr(self, 'infer_weight', 0.0)}, "
            f"final_weight={self.final_weight}, "
            f"judge_model={self.judge_model!r}",
            flush=True,
        )


        for idx in range(len(data)):
            data_item = data[idx]
            # print(data_item)

            trajectory_info = _as_plain_object(trajectory_infos[idx]) or {}
            extra_info = _as_plain_object(data_item.non_tensor_batch.get("extra_info", {})) or {}
            reward_model = _as_plain_object(data_item.non_tensor_batch.get("reward_model", {})) or {}
            trajectory = _as_plain_object(data_item.non_tensor_batch.get("trajectory", [])) or []
            
            question = str(extra_info.get("question", "")).strip()
            final_claims = list(trajectory_info.get("final_claims", []) or [])
            valid_trajectory = int(trajectory_info.get("valid_trajectory", 1))
            submitted = bool(trajectory_info.get("submitted_answer_present", False))
            ground_truth = reward_model.get("ground_truth")
            prompt_type = self._resolve_judge_prompt_type(extra_info)
            
            infer_steps = _extract_infer_steps_from_trajectory(trajectory)
            claim_var_map = _build_claim_var_map(final_claims)

            if idx < 3:
                print(f"[DIAG][VeriGraphReward] sample {idx}: "
                      f"valid_trajectory={valid_trajectory}, submitted={submitted}, "
                      f"final_claims_count={len(final_claims)}, "
                      f"has_ground_truth={_has_ground_truth(ground_truth)}, "
                      f"ground_truth_type={type(ground_truth).__name__}, "
                      f"ground_truth_repr={repr(ground_truth)[:200]}, "
                      f"reward_model_keys={list(reward_model.keys()) if isinstance(reward_model, dict) else type(reward_model).__name__}, "
                      f"termination_reason={trajectory_info.get('termination_reason', 'N/A')}", flush=True)

            # Track which conditions fail
            if not (self.final_weight > 0):
                _diag_no_final_weight += 1
            if not valid_trajectory:
                _diag_invalid_traj += 1
            if not submitted:
                _diag_not_submitted += 1
            if not final_claims:
                _diag_no_claims += 1
            if not _has_ground_truth(ground_truth):
                _diag_no_gt += 1

            if self.final_weight > 0 and valid_trajectory and submitted and final_claims and _has_ground_truth(ground_truth):
                _diag_passed += 1
                judge_lookup[idx] = len(judge_payloads)
                judge_payloads.append(
                    {
                        "system_prompt": self._select_system_prompt(prompt_type),
                        "user_prompt": self._build_judge_prompt(question, final_claims, ground_truth),
                    }
                )
            
            # 计算推理步骤的奖励
            if getattr(self, "infer_weight", 0.0) > 0 and valid_trajectory and infer_steps:
                for step_i, step in enumerate(infer_steps):
                    premise_texts = [
                        claim_var_map[var]
                        for var in step.get("premise_vars", [])
                        if var in claim_var_map and claim_var_map[var].strip()
                    ]
                    conclusion = str(step.get("conclusion", "")).strip()
                    reasoning = str(step.get("reasoning", "")).strip()
    
                    if not premise_texts or not conclusion:
                        continue
    
                    infer_judge_lookup[(idx, step_i)] = len(infer_judge_payloads)
                    infer_judge_payloads.append(
                        {
                            "system_prompt": self.infer_judge_prompt,
                            "user_prompt": _build_infer_judge_prompt(
                                question=question,
                                premise_texts=premise_texts,
                                conclusion=conclusion,
                                reasoning=reasoning,
                            ),
                        }
                    )

        print(f"[DIAG][VeriGraphReward] Judge condition summary: "
              f"total={_diag_total}, passed={_diag_passed}, "
              f"no_final_weight={_diag_no_final_weight}, "
              f"invalid_traj={_diag_invalid_traj}, "
              f"not_submitted={_diag_not_submitted}, "
              f"no_claims={_diag_no_claims}, "
              f"no_ground_truth={_diag_no_gt}, "
              f"judge_payloads={len(judge_payloads)}", flush=True)

        judge_results = self._score_final_claims_batch(judge_payloads)
        infer_judge_results = self._score_infer_steps_batch(infer_judge_payloads)

        for idx in range(len(data)):
            data_item = data[idx]

            # infer_score计算
            trajectory = _as_plain_object(data_item.non_tensor_batch.get("trajectory", [])) or []
            infer_steps = _extract_infer_steps_from_trajectory(trajectory)
            infer_scores = []
            infer_reasons = []
            for step_i, step in enumerate(infer_steps):
                key = (idx, step_i)
                if key not in infer_judge_lookup:
                    continue
                step_score, step_reason = infer_judge_results[infer_judge_lookup[key]]
                infer_scores.append(float(step_score))
                infer_reasons.append(step_reason)
    
            if len(infer_scores) == 0:
                infer_reward = 0.0
            else:
                infer_reward = float(sum(infer_scores) / len(infer_scores))


            _response_str, valid_response_length = self._decode_response(data_item)
            trajectory_info = _as_plain_object(trajectory_infos[idx]) or {}
            extra_info = _as_plain_object(data_item.non_tensor_batch.get("extra_info", {})) or {}
            reward_model = _as_plain_object(data_item.non_tensor_batch.get("reward_model", {})) or {}
            valid_trajectory = int(trajectory_info.get("valid_trajectory", 1))
            submitted = bool(trajectory_info.get("submitted_answer_present", False))
            final_claims = list(trajectory_info.get("final_claims", []) or [])
            tool_stats = dict(trajectory_info.get("tool_stats", {}) or {})
            prompt_type = self._resolve_judge_prompt_type(extra_info)
            ground_truth = reward_model.get("ground_truth")
            termination_reason = str(trajectory_info.get("termination_reason", "") or "")

            process_reward = float(tool_stats.get("process_reward", 0.0))
            if valid_trajectory == 0 or int(tool_stats.get("total_calls", 0)) == 0:
                process_reward = 0.0

            final_reward = 0.0
            judge_reason = "skipped"
            if not _has_ground_truth(ground_truth):
                judge_reason = "missing_ground_truth"
            elif valid_trajectory and submitted and final_claims and idx in judge_lookup:
                final_reward, judge_reason = judge_results[judge_lookup[idx]]

            if termination_reason in NEGATIVE_TERMINATION_REASONS:
                process_reward = 0.0
                infer_reward = 0.0
                final_reward = 0.0
                failure_penalty = -1.0
                total_reward = -1.0
            else:
                failure_penalty = 0.0
                total_reward = (
                    self.process_weight * process_reward
                    + self.infer_weight * infer_reward
                    + self.final_weight * final_reward
                )

            reward_tensor[idx, max(0, valid_response_length - 1)] = total_reward
            total_rewards.append(total_reward)

            reward_extra_info["reward/process"].append(process_reward)
            reward_extra_info["reward/final_judge"].append(final_reward)
            reward_extra_info["reward/total"].append(total_reward)
            reward_extra_info["trajectory/tool_success_rate"].append(process_reward)
            reward_extra_info["trajectory/valid_submit_rate"].append(float(valid_trajectory and submitted))
            # reward_extra_info["judge/reason"].append(judge_reason)
            # reward_extra_info["judge/prompt_type"].append(prompt_type)
            reward_extra_info["trajectory/final_claim_count"].append(len(final_claims))

            reward_extra_info["reward/infer"].append(infer_reward)
            reward_extra_info["reward/failure_penalty"].append(failure_penalty)
            reward_extra_info["trajectory/infer_count"].append(len(infer_scores))
            reward_extra_info["trajectory/infer_success_rate"].append(
                float(sum(1 for s in infer_scores if s > 0) / len(infer_scores)) if infer_scores else 0.0
            )

            judge_debug_info["judge/infer_reasons"].append(infer_reasons)
            
            judge_debug_info["judge/reason"].append(judge_reason)
            judge_debug_info["judge/prompt_type"].append(prompt_type)
            print(f"[DIAG][VeriGraphReward] sample {idx}: process_reward={process_reward:.4f}, infer_reward={infer_reward:.4f}, final_reward={final_reward:.4f}, total_reward={total_reward:.4f}, judge_reason={judge_reason}, prompt_type={prompt_type}", flush=True)
            

        data.batch["acc"] = torch.tensor(total_rewards, dtype=torch.float32, device=reward_tensor.device)

        if return_dict:
            return {
                "reward_tensor": reward_tensor,
                "reward_extra_info": reward_extra_info,
                "judge_debug_info": judge_debug_info,
            }
        return reward_tensor
